name: Phronesis
favicon: null
layout_spectrum: 0.99433
typography_spectrum: 0.75699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f8be5'
    - '#d4d4d4'
    - '#619800'
    - '#752300'
  brandStrength: 0.3473729544784874
  lightness: 1
  saturation: 0.9073141489643604
  rhythmicContrast: 0.6971726266201586
purpose: []
